export const RECEIVE_HOMEDATA = 'receive_homedata'
export const RECEIVE_CATEGORY = 'receive_category'
export const RECEIVE_SEARCHINITIAL = 'receive_searchinitial'
export const RECEIVE_THINGSNAV = 'receive_thingsNav'
export const RECEIVE_THINGSDATA = 'receive_thingsdata'
export const RECEIVE_USER = 'receive_user'
export const LOGOUT = 'logout'
